"""add feedback to module

Revision ID: 039d21949605
Revises: 9f12acac29a6
Create Date: 2025-12-29 13:16:16.907938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039d21949605'
down_revision = '9f12acac29a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_feedback_given', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_column('is_feedback_given')
        batch_op.drop_column('feedback')

    # ### end Alembic commands ###
